language: python
python:
   - "2.7"
   - "3.6"

dist: trusty
os:
  - linux

# command to install dependencies and data
install:
    - "pip install -r requirements-dev.txt"
    - "python -m spacy download en_core_web_sm"
    - "python -m spacy link en_core_web_sm en"
    - "python -m spacy download es_core_news_sm"
    - "python -m spacy link es_core_news_sm es"
    - "python -m textacy download capitol_words"

# command to run tests
script: "python -m pytest -v"
