name: docs

on:
  push:
    branches: [ main ]
  pull_request:  # run on all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [html, text]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e '.[docs]'
    - name: make ${{ matrix.build-type }} docs
      run: |
        cd docs && make ${{ matrix.build-type }}
